packages:
  - "apps/*"
  - "packages/*"

patchedDependencies:
  y-excalidraw@2.0.12: patches/y-excalidraw@2.0.12.patch

overrides:
  vite: 7.3.1
  vitest: 4.1.8
  typescript: 6.0.3
  "@excalidraw/excalidraw": 0.18.1
  react: 19.2.7
  react-dom: 19.2.7
