/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Clean old caches from previous versions
cleanupOutdatedCaches();

// Let the main thread control when the new SW activates (registerType: "prompt").
// Do NOT call skipWaiting/clients.claim here — that would bypass the update prompt
// and cause surprise reloads.

// Push notification handler
self.addEventListener("push", (event) => {
  let data: { title: string; body: string; data?: { url?: string } } = {
    title: "Ripple",
    body: "You have a new notification",
  };
  try {
    if (event.data) {
      data = JSON.parse(event.data.text()) as typeof data;
    }
  } catch {
    // Malformed payload — fall through to default
  }

  const options: NotificationOptions = {
    body: data.body,
    icon: "/icons/icon-192.png",
    badge: "/icons/icon-192.png",
    data: { url: data.data?.url },
  };

  // Always call showNotification so the browser never shows its own fallback
  // ("[App name], tap to copy the URL for this app") due to userVisibleOnly: true.
  event.waitUntil(self.registration.showNotification(data.title, options));
});

// Notification click handler
self.addEventListener("notificationclick", (event) => {
  const notification = event.notification;
  const urlToOpen = new URL(
    notification.data?.url || "/",
    self.location.origin,
  ).href;

  notification.close();

  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((windowClients) => {
        for (const client of windowClients) {
          if (client.url === urlToOpen) {
            return client.focus();
          }
        }
        return self.clients.openWindow(urlToOpen);
      }),
  );
});
