import { Switch } from "@/components/ui/switch";
import { useMutation } from "convex/react";
import { useQuery } from "convex-helpers/react/cache";
import { useState } from "react";
import { toast } from "sonner";
import { api } from "@convex/_generated/api";
import type { Id } from "@convex/_generated/dataModel";
import { FeatureKey } from "@ripple/shared/enums/features";

type Props = { workspaceId: Id<"workspaces">; isAdmin: boolean };

/**
 * The switch for the workspace assistant. It flips the `ai_assistant`
 * entitlement through the same mutation the integration capabilities use;
 * the backend creates the bot user on the first enable and keeps it on
 * disable, so the toggle is safe to flip either way at any time.
 *
 * Non-admins see the state and who to ask.
 */
export function WorkspaceAssistantSection({ workspaceId, isAdmin }: Props) {
  const feature = useQuery(api.integrations.core.entitlements.getWorkspaceFeature, {
    workspaceId,
    featureKey: FeatureKey.AI_ASSISTANT,
  });
  const assistant = useQuery(api.chatAssistant.get, { workspaceId });
  const setFeature = useMutation(api.integrations.core.entitlements.setWorkspaceFeature);
  const [pending, setPending] = useState(false);

  if (feature === undefined) return null;
  const enabled = feature.enabled;

  const handleToggle = (next: boolean) => {
    setPending(true);
    setFeature({ workspaceId, featureKey: FeatureKey.AI_ASSISTANT, enabled: next })
      .then(() => {
        toast.success(next ? "Assistant enabled" : "Assistant disabled");
      })
      .catch((err: unknown) => {
        toast.error("Could not update the assistant", {
          description: err instanceof Error ? err.message : "Please try again",
        });
      })
      .finally(() => setPending(false));
  };

  const mentionName = assistant?.name ?? "Assistant";

  return (
    <div className="space-y-4">
      <div className="flex items-start justify-between gap-3 rounded-md border px-3 py-3">
        <div className="min-w-0">
          <div className="text-sm font-medium">Answer when mentioned in chat</div>
          <p className="text-xs text-muted-foreground">
            {isAdmin
              ? `Type @${mentionName} in any channel to ask it something. It reads the channel it is asked in, and nothing else. Replies are generated by an AI model.`
              : enabled
                ? `Enabled. Type @${mentionName} in any channel to ask it something.`
                : "Disabled. Ask a workspace admin to enable it."}
          </p>
        </div>
        {isAdmin ? (
          <Switch
            checked={enabled}
            disabled={pending}
            onCheckedChange={handleToggle}
            aria-label="Toggle the workspace assistant"
          />
        ) : null}
      </div>
    </div>
  );
}
